include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: warning
    use_key_in_widget_constructors: ignore
    use_build_context_synchronously: ignore
linter:
  rules:
    avoid_redundant_argument_values: true
    prefer_relative_imports: true